CREATE TYPE "seat_class_enum" AS ENUM (
  'Negocios',
  'Económica'
);

CREATE TYPE "reservation_status_enum" AS ENUM (
  'Activa',
  'Modificada',
  'Cancelada'
);

CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar(100) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "is_vip" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "seat_prices" (
  "price_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seat_class" seat_class_enum UNIQUE NOT NULL,
  "base_price" numeric(10,2) NOT NULL
);

CREATE TABLE "seats" (
  "seat_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seat_number" varchar(5) UNIQUE NOT NULL,
  "seat_class" seat_class_enum NOT NULL,
  "is_occupied" boolean DEFAULT false
);

CREATE TABLE "passengers" (
  "passenger_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar(100) NOT NULL,
  "cui" char(13) UNIQUE NOT NULL,
  "department" varchar(50),
  "municipality" varchar(50)
);

CREATE TABLE "reservations" (
  "reservation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "seat_id" int,
  "passenger_id" int,
  "has_luggage" boolean NOT NULL,
  "reservation_date" timestamp DEFAULT (now()),
  "status" reservation_status_enum DEFAULT 'Activa',
  "price_base" numeric(10,2) NOT NULL,
  "discount" numeric(10,2) DEFAULT 0,
  "modification_fee" numeric(10,2) DEFAULT 0,
  "total_price" numeric(10,2) NOT NULL,
  "modified_at" timestamp
);

COMMENT ON TABLE "users" IS 'Usuarios registrados del sistema. Se marcan como VIP cuando tienen más de 5 reservas.';

COMMENT ON COLUMN "users"."email" IS 'Solo dominios @gmail.com o @outlook.com';

COMMENT ON TABLE "seat_prices" IS 'Precio base según tipo de asiento.';

COMMENT ON TABLE "seats" IS 'Listado de asientos disponibles, indicando si están ocupados o no.';

COMMENT ON COLUMN "seats"."seat_number" IS 'Ejemplo: A1, B2, C3';

COMMENT ON TABLE "passengers" IS 'Persona asociada a la reserva. Puede diferir del usuario que reservó.';

COMMENT ON COLUMN "passengers"."cui" IS 'Formato válido con departamento y municipio';

ALTER TABLE "reservations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "reservations" ADD FOREIGN KEY ("seat_id") REFERENCES "seats" ("seat_id");

ALTER TABLE "reservations" ADD FOREIGN KEY ("passenger_id") REFERENCES "passengers" ("passenger_id");
