-- =====================================================
-- Migración 005: Soft Delete y Sistema de Auditoría
-- =====================================================
-- Descripción: Agrega soft delete a las reservas y crea
-- una tabla de auditoría detallada para historial de
-- cancelaciones y cambios.

-- 1. Agregar columna deleted_at a reservations (soft delete)
ALTER TABLE "reservations" ADD COLUMN "deleted_at" timestamp;

-- 2. Crear tabla de auditoría detallada
CREATE TABLE "reservation_audit" (
  "audit_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL,
  "reservation_id" INT NOT NULL,
  "action" VARCHAR(50) NOT NULL, -- 'created', 'modified', 'cancelled', 'restored'
  "action_reason" VARCHAR(255), -- Razón de la acción (opcional)
  "cancelled_at" TIMESTAMP DEFAULT (now()),
  "details" JSONB, -- Almacena detalles de lo que cambió
  "ip_address" VARCHAR(45), -- IPv4 o IPv6
  "user_agent" VARCHAR(512), -- Información del navegador/cliente
  FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE,
  FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("reservation_id") ON DELETE CASCADE
);

-- 3. Crear índices para búsquedas rápidas
CREATE INDEX "idx_reservation_audit_user" ON "reservation_audit"("user_id");
CREATE INDEX "idx_reservation_audit_reservation" ON "reservation_audit"("reservation_id");
CREATE INDEX "idx_reservation_audit_action" ON "reservation_audit"("action");
CREATE INDEX "idx_reservation_audit_date" ON "reservation_audit"("cancelled_at");
CREATE INDEX "idx_reservations_deleted_at" ON "reservations"("deleted_at");

-- 4. Vista para obtener reservas activas (no eliminadas)
CREATE VIEW "active_reservations" AS
SELECT * FROM "reservations" WHERE "deleted_at" IS NULL;

-- 5. Vista para obtener historial de cancelaciones de un usuario
CREATE VIEW "user_cancellation_history" AS
SELECT 
  u.user_id,
  u.full_name AS user_name,
  u.email,
  ra.audit_id,
  ra.reservation_id,
  ra.action,
  ra.action_reason,
  ra.cancelled_at,
  s.seat_number,
  s.seat_class,
  p.full_name AS passenger_name,
  p.cui,
  r.price_base,
  r.discount,
  r.total_price
FROM "reservation_audit" ra
JOIN "users" u ON u.user_id = ra.user_id
JOIN "reservations" r ON r.reservation_id = ra.reservation_id
LEFT JOIN "seats" s ON s.seat_id = r.seat_id
LEFT JOIN "passengers" p ON p.passenger_id = r.passenger_id
WHERE ra.action = 'cancelled'
ORDER BY ra.cancelled_at DESC;

-- 6. Función para registrar auditoría automáticamente
CREATE OR REPLACE FUNCTION "log_reservation_audit"()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'DELETE') THEN
    INSERT INTO "reservation_audit"(user_id, reservation_id, action, cancelled_at, details)
    VALUES (
      OLD.user_id,
      OLD.reservation_id,
      'deleted',
      now(),
      jsonb_build_object(
        'deleted_at', now(),
        'seat_id', OLD.seat_id,
        'status', OLD.status,
        'total_price', OLD.total_price
      )
    );
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- 7. Trigger para auditoría automática (no se usa actualmente pero está disponible)
CREATE TRIGGER "reservation_delete_audit" AFTER DELETE ON "reservations"
FOR EACH ROW EXECUTE FUNCTION "log_reservation_audit"();

COMMENT ON TABLE "reservation_audit" IS 'Bitácora detallada de cambios en reservas: creación, modificación, cancelación y restauración.';
COMMENT ON COLUMN "reservation_audit"."action_reason" IS 'Razón de la cancelación (ej: "Cambio de planes", "No disponibilidad", etc)';
COMMENT ON COLUMN "reservation_audit"."details" IS 'Datos JSON con detalles específicos de la acción realizada';
COMMENT ON VIEW "active_reservations" IS 'Reservas que no han sido eliminadas (deleted_at IS NULL)';
COMMENT ON VIEW "user_cancellation_history" IS 'Historial de cancelaciones de un usuario con detalles completos';
