# Dockerfile.dev - solo para desarrollo (hot reload)
FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install

# Copiamos el código fuente
COPY . .

# Puerto de desarrollo de Angular
EXPOSE 4200

# Comando por defecto
CMD ["npm", "run", "start"]
